name: zego_express_engine
summary: Zego RTC SDK for Flutter
description: ZegoExpressEngine Flutter SDK is a flutter plugin wrapper based on ZEGO Express RTC SDK (Native & Web), providing live video and real-time audio/video services.
version: 3.18.0
homepage: https://zego.im

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: im.zego.zego_express_engine
        pluginClass: ZegoExpressEnginePlugin
      ios:
        pluginClass: ZegoExpressEnginePlugin
      macos:
        pluginClass: ZegoExpressEnginePlugin
      windows:
        pluginClass: ZegoExpressEnginePlugin
      linux:
        pluginClass: ZegoExpressEnginePlugin
      web:
        pluginClass: ZegoExpressEngineWeb
        fileName: zego_express_engine_web.dart
  assets:
    - assets/ZegoExpressWebFlutterWrapper.js
